require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Max: 32
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - db/migrate/*.rb
Hc/RailsSpecificActionName:
  Exclude:
    - app/controllers/users/omniauth_callbacks_controller.rb
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "config/environments/*.rb"
    - "Gemfile"
    - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - "config/routes.rb"
