services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    image: rails_template:latest
    command: bundle exec bin/dev
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
volumes:
  db:
  bundle:
  node_modules:
